-- VegaPal — fresh Supabase database bootstrap
-- Generated by: node scripts/build-bootstrap-sql.mjs
-- Do not edit by hand; change files in supabase/migrations/ and regenerate.
--
-- Prerequisites (Supabase SQL Editor on a NEW project):
--   - Auth schema exists (default on Supabase)
--   - Extensions: pgcrypto (gen_random_uuid) — enabled below
--
-- After this script:
--   1. Configure Auth URLs (see docs/MIGRATION_GUIDE.md)
--   2. Set Vercel env vars to the new project
--   3. Promote first admin: UPDATE public.profiles SET role = 'admin' WHERE email = 'you@example.com';
--

CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ========== 20260624073831_6545babe-9c15-45c1-91aa-19476cbe6545.sql ==========

-- PROFILES
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  name TEXT NOT NULL DEFAULT '',
  business TEXT,
  company_address TEXT,
  website TEXT,
  contact_email TEXT,
  logo_url TEXT,
  brand_color TEXT NOT NULL DEFAULT '#16C784',
  wallet TEXT NOT NULL DEFAULT 'TQn9Y2khEsLJW1ChVWFMSMeRDow5KcbLSE',
  network TEXT NOT NULL DEFAULT 'TRC20',
  email_notifications BOOLEAN NOT NULL DEFAULT true,
  invoice_updates BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own profile" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Users insert own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- INVOICES
CREATE TABLE public.invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  number TEXT NOT NULL,
  client_name TEXT NOT NULL,
  client_email TEXT NOT NULL,
  client_company TEXT,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date DATE NOT NULL,
  subtotal NUMERIC(20,2) NOT NULL DEFAULT 0,
  discount NUMERIC(20,2) NOT NULL DEFAULT 0,
  tax NUMERIC(20,2) NOT NULL DEFAULT 0,
  total NUMERIC(20,2) NOT NULL DEFAULT 0,
  wallet_address TEXT NOT NULL,
  network TEXT NOT NULL,
  seller_name TEXT NOT NULL,
  seller_business TEXT,
  seller_email TEXT NOT NULL,
  seller_address TEXT,
  seller_logo_url TEXT,
  brand_color TEXT NOT NULL DEFAULT '#16C784',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX invoices_user_id_idx ON public.invoices(user_id);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.invoices TO authenticated;
GRANT SELECT ON public.invoices TO anon;
GRANT ALL ON public.invoices TO service_role;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owner manages invoices" ON public.invoices FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Public can view invoices" ON public.invoices FOR SELECT TO anon USING (true);

-- INVOICE ITEMS
CREATE TABLE public.invoice_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id UUID NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0,
  description TEXT NOT NULL,
  quantity NUMERIC(20,4) NOT NULL DEFAULT 1,
  unit_price NUMERIC(20,2) NOT NULL DEFAULT 0,
  total NUMERIC(20,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX invoice_items_invoice_id_idx ON public.invoice_items(invoice_id);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.invoice_items TO authenticated;
GRANT SELECT ON public.invoice_items TO anon;
GRANT ALL ON public.invoice_items TO service_role;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owner manages invoice items" ON public.invoice_items FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.invoices i WHERE i.id = invoice_id AND i.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.invoices i WHERE i.id = invoice_id AND i.user_id = auth.uid()));
CREATE POLICY "Public can view invoice items" ON public.invoice_items FOR SELECT TO anon USING (true);

-- updated_at trigger
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER invoices_updated_at BEFORE UPDATE ON public.invoices FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, business, contact_email)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    NULLIF(NEW.raw_user_meta_data->>'business', ''),
    NEW.email
  );
  RETURN NEW;
END $$;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ========== 20260624073841_bdff3ce9-427f-42e7-830d-f852b5581113.sql ==========

REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;


-- ========== 20260625120000_invoice_phase1.sql ==========

-- Phase 1: invoice currency, reference fields, display/payment JSONB, terms

ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS invoice_currency TEXT NOT NULL DEFAULT 'USDT',
  ADD COLUMN IF NOT EXISTS po_number TEXT,
  ADD COLUMN IF NOT EXISTS reference_number TEXT,
  ADD COLUMN IF NOT EXISTS project_code TEXT,
  ADD COLUMN IF NOT EXISTS terms_and_conditions TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS display_options JSONB NOT NULL DEFAULT '{
    "showVegapalLogo": true,
    "showSellerInfo": true,
    "showClientInfo": true,
    "showDueDate": true,
    "showStatus": true,
    "showDiscount": false,
    "showTax": false,
    "showNotes": false,
    "showTerms": false,
    "showPaymentInstructions": true,
    "showPoNumber": false,
    "showReferenceNumber": false,
    "showProjectCode": false
  }'::jsonb,
  ADD COLUMN IF NOT EXISTS payment_methods JSONB NOT NULL DEFAULT '{
    "method": "crypto",
    "crypto": {
      "enabled": true,
      "currency": "USDT",
      "network": "TRON TRC20",
      "walletAddress": ""
    },
    "bank": { "enabled": false },
    "cash": { "enabled": false }
  }'::jsonb;

-- Backfill existing rows from legacy wallet_address / network columns
UPDATE public.invoices
SET
  invoice_currency = COALESCE(invoice_currency, 'USDT'),
  terms_and_conditions = COALESCE(terms_and_conditions, ''),
  display_options = COALESCE(display_options, '{
    "showVegapalLogo": true,
    "showSellerInfo": true,
    "showClientInfo": true,
    "showDueDate": true,
    "showStatus": true,
    "showDiscount": false,
    "showTax": false,
    "showNotes": false,
    "showTerms": false,
    "showPaymentInstructions": true,
    "showPoNumber": false,
    "showReferenceNumber": false,
    "showProjectCode": false
  }'::jsonb),
  payment_methods = CASE
    WHEN payment_methods IS NULL
      OR payment_methods = '{}'::jsonb
      OR payment_methods = '{
        "method": "crypto",
        "crypto": {
          "enabled": true,
          "currency": "USDT",
          "network": "TRON TRC20",
          "walletAddress": ""
        },
        "bank": { "enabled": false },
        "cash": { "enabled": false }
      }'::jsonb
    THEN jsonb_build_object(
      'method', 'crypto',
      'crypto', jsonb_build_object(
        'enabled', true,
        'currency', 'USDT',
        'network', CASE network
          WHEN 'TRC20' THEN 'TRON TRC20'
          WHEN 'ERC20' THEN 'Ethereum ERC20'
          WHEN 'BEP20' THEN 'BNB Smart Chain BEP20'
          ELSE COALESCE(NULLIF(network, ''), 'TRON TRC20')
        END,
        'walletAddress', wallet_address
      ),
      'bank', jsonb_build_object('enabled', false),
      'cash', jsonb_build_object('enabled', false)
    )
    ELSE payment_methods
  END
WHERE true;


-- ========== 20260626120000_tighten_public_invoice_rls.sql ==========

-- Tighten anonymous read access: public pay links should not expose draft invoices.

DROP POLICY IF EXISTS "Public can view invoices" ON public.invoices;
CREATE POLICY "Public can view non-draft invoices"
  ON public.invoices
  FOR SELECT
  TO anon
  USING (status <> 'draft');

DROP POLICY IF EXISTS "Public can view invoice items" ON public.invoice_items;
CREATE POLICY "Public can view items of non-draft invoices"
  ON public.invoice_items
  FOR SELECT
  TO anon
  USING (
    EXISTS (
      SELECT 1
      FROM public.invoices i
      WHERE i.id = invoice_id
        AND i.status <> 'draft'
    )
  );


-- ========== 20260627120000_admin_plans.sql ==========

-- Admin roles, subscription plans, and account status on profiles.

CREATE TYPE public.user_plan AS ENUM ('free', 'pro', 'business');
CREATE TYPE public.user_role AS ENUM ('user', 'admin');

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS plan public.user_plan NOT NULL DEFAULT 'free',
  ADD COLUMN IF NOT EXISTS role public.user_role NOT NULL DEFAULT 'user',
  ADD COLUMN IF NOT EXISTS is_disabled BOOLEAN NOT NULL DEFAULT false;

-- Block authenticated users from changing privileged fields on their own row.
-- Service-role updates (auth.uid() IS NULL) are allowed for admin API handlers.
CREATE OR REPLACE FUNCTION public.protect_profile_privileged_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN NEW;
  END IF;

  IF auth.uid() = OLD.id THEN
    IF NEW.role IS DISTINCT FROM OLD.role THEN
      RAISE EXCEPTION 'Cannot change role';
    END IF;
    IF NEW.plan IS DISTINCT FROM OLD.plan THEN
      RAISE EXCEPTION 'Cannot change plan';
    END IF;
    IF NEW.is_disabled IS DISTINCT FROM OLD.is_disabled THEN
      RAISE EXCEPTION 'Cannot change account status';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_protect_privileged_fields ON public.profiles;
CREATE TRIGGER profiles_protect_privileged_fields
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_profile_privileged_fields();

-- Grant admin access manually after migration, e.g.:
-- UPDATE public.profiles SET role = 'admin' WHERE email = 'you@example.com';


-- ========== 20260629120000_grant_initial_admin.sql ==========

-- Grant initial admin when no admin account exists yet.
-- Safe to re-run: skips if any active admin profile already exists.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE role = 'admin'
      AND NOT is_disabled
  ) THEN
    UPDATE public.profiles
    SET role = 'admin'
    WHERE lower(trim(email)) = lower('bossvegapal@outlook.com');

    IF NOT FOUND THEN
      RAISE NOTICE 'No profile for bossvegapal@outlook.com — register and sign in once, then run: UPDATE public.profiles SET role = ''admin'' WHERE lower(email) = lower(''bossvegapal@outlook.com'');';
    END IF;
  END IF;
END $$;


-- ========== 20260630120000_invoice_plan_limit.sql ==========

-- Enforce Free plan monthly document limit (3) at the database layer.

CREATE OR REPLACE FUNCTION public.count_user_invoices_this_month(p_user_id uuid)
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COUNT(*)::integer
  FROM public.invoices
  WHERE user_id = p_user_id
    AND created_at >= date_trunc('month', timezone('UTC', now()))
    AND created_at < date_trunc('month', timezone('UTC', now())) + interval '1 month';
$$;

CREATE OR REPLACE FUNCTION public.enforce_invoice_plan_limit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  user_plan public.user_plan;
  monthly_count integer;
BEGIN
  SELECT plan INTO user_plan FROM public.profiles WHERE id = NEW.user_id;
  IF user_plan IS NULL THEN
    user_plan := 'free';
  END IF;

  IF user_plan = 'free' THEN
    monthly_count := public.count_user_invoices_this_month(NEW.user_id);
    IF monthly_count >= 5 THEN
      RAISE EXCEPTION 'FREE_PLAN_INVOICE_LIMIT'
        USING MESSAGE = 'You have reached the Free plan limit of 3 documents this month. Upgrade to Pro to create unlimited invoices.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS invoices_enforce_plan_limit ON public.invoices;
CREATE TRIGGER invoices_enforce_plan_limit
  BEFORE INSERT ON public.invoices
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_invoice_plan_limit();

CREATE OR REPLACE FUNCTION public.get_invoice_plan_usage()
RETURNS TABLE (
  plan public.user_plan,
  invoices_this_month integer,
  monthly_limit integer
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    COALESCE(p.plan, 'free'::public.user_plan),
    public.count_user_invoices_this_month(auth.uid()),
    CASE WHEN COALESCE(p.plan, 'free') = 'free' THEN 5 ELSE NULL END
  FROM public.profiles p
  WHERE p.id = auth.uid();
$$;

REVOKE ALL ON FUNCTION public.count_user_invoices_this_month(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.enforce_invoice_plan_limit() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_invoice_plan_usage() TO authenticated;


-- ========== 20260630140000_admin_audit_logs.sql ==========

-- Admin audit logs: service-role writes only; no client policies (deny by default under RLS).
CREATE TABLE public.admin_audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_user_id UUID NOT NULL REFERENCES auth.users(id),
  target_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  old_value JSONB,
  new_value JSONB,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.admin_audit_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX admin_audit_logs_target_user_id_idx ON public.admin_audit_logs (target_user_id);
CREATE INDEX admin_audit_logs_created_at_idx ON public.admin_audit_logs (created_at DESC);

COMMENT ON TABLE public.admin_audit_logs IS 'Admin actions audit trail. Access via service role / admin API only.';


-- ========== 20260630150000_admin_audit_logs_grants.sql ==========

-- service_role needs table privileges (RLS alone is not enough for PostgREST).
GRANT ALL ON public.admin_audit_logs TO service_role;


-- ========== 20260729120000_invoice_document_lifecycle.sql ==========

-- Document type, lifecycle, and payment status (backward-compatible with legacy `status`)

ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS document_type TEXT NOT NULL DEFAULT 'tax_invoice',
  ADD COLUMN IF NOT EXISTS document_status TEXT NOT NULL DEFAULT 'issued',
  ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'unpaid';

ALTER TABLE public.invoices
  DROP CONSTRAINT IF EXISTS invoices_document_type_check,
  ADD CONSTRAINT invoices_document_type_check
    CHECK (document_type IN ('quotation', 'proforma_invoice', 'tax_invoice'));

ALTER TABLE public.invoices
  DROP CONSTRAINT IF EXISTS invoices_document_status_check,
  ADD CONSTRAINT invoices_document_status_check
    CHECK (document_status IN ('draft', 'issued', 'accepted', 'rejected', 'cancelled', 'expired'));

ALTER TABLE public.invoices
  DROP CONSTRAINT IF EXISTS invoices_payment_status_check,
  ADD CONSTRAINT invoices_payment_status_check
    CHECK (payment_status IN (
      'not_applicable', 'unpaid', 'partially_paid', 'paid', 'overdue', 'refunded'
    ));

-- Backfill from legacy status
UPDATE public.invoices
SET
  document_type = COALESCE(document_type, 'tax_invoice'),
  document_status = CASE status
    WHEN 'draft' THEN 'draft'
    WHEN 'cancelled' THEN 'cancelled'
    ELSE 'issued'
  END,
  payment_status = CASE
    WHEN status = 'draft' THEN 'unpaid'
    WHEN status = 'cancelled' THEN 'unpaid'
    WHEN status = 'paid' THEN 'paid'
    WHEN status = 'overdue' THEN 'overdue'
    ELSE 'unpaid'
  END
WHERE true;

-- Quotations created after this migration will set not_applicable in app; existing rows stay tax_invoice.

CREATE INDEX IF NOT EXISTS invoices_user_document_type_idx
  ON public.invoices (user_id, document_type);

CREATE INDEX IF NOT EXISTS invoices_user_payment_status_idx
  ON public.invoices (user_id, payment_status);

CREATE INDEX IF NOT EXISTS invoices_user_document_status_idx
  ON public.invoices (user_id, document_status);

-- Per-user, per-type sequential numbering
CREATE TABLE IF NOT EXISTS public.invoice_document_sequences (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL,
  last_number INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, document_type),
  CONSTRAINT invoice_document_sequences_type_check
    CHECK (document_type IN ('quotation', 'proforma_invoice', 'tax_invoice'))
);

ALTER TABLE public.invoice_document_sequences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own invoice sequences"
  ON public.invoice_document_sequences
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

GRANT SELECT, INSERT, UPDATE ON public.invoice_document_sequences TO authenticated;
GRANT ALL ON public.invoice_document_sequences TO service_role;

-- Seed sequences from existing invoice numbers (INV-0001 → 1, etc.)
INSERT INTO public.invoice_document_sequences (user_id, document_type, last_number)
SELECT
  user_id,
  COALESCE(document_type, 'tax_invoice'),
  COALESCE(
    MAX(
      CASE
        WHEN number ~ '^[A-Z]+-[0-9]+$'
        THEN NULLIF(regexp_replace(number, '^[A-Z]+-', ''), '')::integer
        ELSE 0
      END
    ),
    0
  )::integer
FROM public.invoices
GROUP BY user_id, COALESCE(document_type, 'tax_invoice')
ON CONFLICT (user_id, document_type)
DO UPDATE SET last_number = GREATEST(
  invoice_document_sequences.last_number,
  EXCLUDED.last_number
);

CREATE OR REPLACE FUNCTION public.allocate_invoice_document_number(p_document_type TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid UUID := auth.uid();
  prefix TEXT;
  next_num INTEGER;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;

  IF p_document_type NOT IN ('quotation', 'proforma_invoice', 'tax_invoice') THEN
    RAISE EXCEPTION 'invalid document type';
  END IF;

  prefix := CASE p_document_type
    WHEN 'quotation' THEN 'QTN'
    WHEN 'proforma_invoice' THEN 'PI'
    ELSE 'INV'
  END;

  INSERT INTO public.invoice_document_sequences (user_id, document_type, last_number)
  VALUES (uid, p_document_type, 1)
  ON CONFLICT (user_id, document_type)
  DO UPDATE SET last_number = invoice_document_sequences.last_number + 1
  RETURNING last_number INTO next_num;

  RETURN prefix || '-' || lpad(next_num::text, 4, '0');
END;
$$;

REVOKE ALL ON FUNCTION public.allocate_invoice_document_number(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.allocate_invoice_document_number(TEXT) TO authenticated;


-- ========== 20260729140000_invoice_discount_tax_modes.sql ==========

-- Percentage vs fixed discount/tax (legacy rows remain fixed amounts in discount/tax columns)

ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS discount_type TEXT NOT NULL DEFAULT 'fixed',
  ADD COLUMN IF NOT EXISTS tax_type TEXT NOT NULL DEFAULT 'fixed',
  ADD COLUMN IF NOT EXISTS discount_rate NUMERIC(8, 4),
  ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(8, 4);

ALTER TABLE public.invoices
  DROP CONSTRAINT IF EXISTS invoices_discount_type_check,
  ADD CONSTRAINT invoices_discount_type_check
    CHECK (discount_type IN ('fixed', 'percentage'));

ALTER TABLE public.invoices
  DROP CONSTRAINT IF EXISTS invoices_tax_type_check,
  ADD CONSTRAINT invoices_tax_type_check
    CHECK (tax_type IN ('fixed', 'percentage'));

UPDATE public.invoices
SET
  discount_type = COALESCE(discount_type, 'fixed'),
  tax_type = COALESCE(tax_type, 'fixed')
WHERE true;


-- ========== 20260729150000_quotation_to_invoice_conversion.sql ==========

-- Quotation → tax invoice conversion (linked documents, one invoice per quotation)

ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS source_document_id UUID REFERENCES public.invoices(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS converted_document_id UUID REFERENCES public.invoices(id) ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS invoices_source_document_id_unique
  ON public.invoices (source_document_id)
  WHERE source_document_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS invoices_converted_document_id_idx
  ON public.invoices (converted_document_id)
  WHERE converted_document_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.convert_quotation_to_invoice(p_quotation_id UUID)
RETURNS TABLE (
  invoice_id UUID,
  invoice_number TEXT,
  already_existed BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid UUID := auth.uid();
  q public.invoices%ROWTYPE;
  existing_id UUID;
  existing_num TEXT;
  new_id UUID;
  new_num TEXT;
  new_issue DATE;
  new_due DATE;
  term_days INTEGER;
  prof_disabled BOOLEAN;
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT is_disabled INTO prof_disabled FROM public.profiles WHERE id = uid;
  IF COALESCE(prof_disabled, false) THEN
    RAISE EXCEPTION 'account_disabled' USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO q FROM public.invoices WHERE id = p_quotation_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'quotation_not_found' USING ERRCODE = 'P0002';
  END IF;

  IF q.user_id IS DISTINCT FROM uid THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  IF q.document_type IS DISTINCT FROM 'quotation' THEN
    RAISE EXCEPTION 'not_a_quotation' USING ERRCODE = 'P0003';
  END IF;

  IF q.document_status = 'cancelled' THEN
    RAISE EXCEPTION 'quotation_cancelled' USING ERRCODE = 'P0004';
  END IF;

  IF q.converted_document_id IS NOT NULL THEN
    SELECT i.id, i.number INTO existing_id, existing_num
    FROM public.invoices i
    WHERE i.id = q.converted_document_id AND i.user_id = uid;
    IF existing_id IS NOT NULL THEN
      invoice_id := existing_id;
      invoice_number := existing_num;
      already_existed := true;
      RETURN NEXT;
      RETURN;
    END IF;
  END IF;

  SELECT i.id, i.number INTO existing_id, existing_num
  FROM public.invoices i
  WHERE i.source_document_id = p_quotation_id AND i.user_id = uid
  LIMIT 1;

  IF existing_id IS NOT NULL THEN
    UPDATE public.invoices
    SET converted_document_id = existing_id
    WHERE id = p_quotation_id AND converted_document_id IS NULL;

    invoice_id := existing_id;
    invoice_number := existing_num;
    already_existed := true;
    RETURN NEXT;
    RETURN;
  END IF;

  new_num := public.allocate_invoice_document_number('tax_invoice');
  new_issue := CURRENT_DATE;
  term_days := GREATEST(0, (q.due_date - q.issue_date));
  new_due := new_issue + term_days;

  INSERT INTO public.invoices (
    user_id,
    number,
    client_name,
    client_email,
    client_company,
    title,
    description,
    terms_and_conditions,
    status,
    document_type,
    document_status,
    payment_status,
    issue_date,
    due_date,
    subtotal,
    discount,
    tax,
    discount_type,
    tax_type,
    discount_rate,
    tax_rate,
    total,
    invoice_currency,
    po_number,
    reference_number,
    project_code,
    display_options,
    payment_methods,
    wallet_address,
    network,
    seller_name,
    seller_business,
    seller_email,
    seller_address,
    seller_logo_url,
    brand_color,
    source_document_id,
    converted_document_id
  ) VALUES (
    uid,
    new_num,
    q.client_name,
    q.client_email,
    q.client_company,
    q.title,
    q.description,
    q.terms_and_conditions,
    'draft',
    'tax_invoice',
    'draft',
    'unpaid',
    new_issue,
    new_due,
    q.subtotal,
    q.discount,
    q.tax,
    COALESCE(q.discount_type, 'fixed'),
    COALESCE(q.tax_type, 'fixed'),
    q.discount_rate,
    q.tax_rate,
    q.total,
    COALESCE(q.invoice_currency, 'USD'),
    q.po_number,
    q.reference_number,
    q.project_code,
    q.display_options,
    q.payment_methods,
    q.wallet_address,
    q.network,
    q.seller_name,
    q.seller_business,
    q.seller_email,
    q.seller_address,
    q.seller_logo_url,
    q.brand_color,
    p_quotation_id,
    NULL
  )
  RETURNING id INTO new_id;

  INSERT INTO public.invoice_items (
    invoice_id,
    position,
    description,
    quantity,
    unit_price,
    total
  )
  SELECT
    new_id,
    ii.position,
    ii.description,
    ii.quantity,
    ii.unit_price,
    ii.total
  FROM public.invoice_items ii
  WHERE ii.invoice_id = p_quotation_id
  ORDER BY ii.position;

  UPDATE public.invoices
  SET converted_document_id = new_id
  WHERE id = p_quotation_id;

  invoice_id := new_id;
  invoice_number := new_num;
  already_existed := false;
  RETURN NEXT;

EXCEPTION
  WHEN unique_violation THEN
    SELECT i.id, i.number INTO existing_id, existing_num
    FROM public.invoices i
    WHERE i.source_document_id = p_quotation_id AND i.user_id = uid
    LIMIT 1;

    IF existing_id IS NOT NULL THEN
      UPDATE public.invoices
      SET converted_document_id = existing_id
      WHERE id = p_quotation_id AND converted_document_id IS NULL;

      invoice_id := existing_id;
      invoice_number := existing_num;
      already_existed := true;
      RETURN NEXT;
      RETURN;
    END IF;
    RAISE;
END;
$$;

REVOKE ALL ON FUNCTION public.convert_quotation_to_invoice(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.convert_quotation_to_invoice(UUID) TO authenticated;


-- ========== 20260826160000_saved_payment_methods.sql ==========

-- Saved payment methods (bank accounts + crypto wallets). Owner-scoped RLS.
-- Invoice payment_methods JSONB remains the historical snapshot; this table is reusable prefs only.

CREATE TABLE IF NOT EXISTS public.payment_methods (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('bank', 'crypto')),
  label TEXT NOT NULL DEFAULT '',
  is_default BOOLEAN NOT NULL DEFAULT false,
  bank_name TEXT,
  account_holder_name TEXT,
  account_name TEXT,
  iban TEXT,
  account_number TEXT,
  swift_bic TEXT,
  bank_currency TEXT,
  payment_reference TEXT,
  crypto_currency TEXT,
  network TEXT,
  wallet_address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at TIMESTAMPTZ,
  CONSTRAINT payment_methods_bank_or_crypto CHECK (
    (type = 'bank' AND (
      coalesce(nullif(trim(iban), ''), nullif(trim(account_number), '')) IS NOT NULL
    ))
    OR
    (type = 'crypto' AND coalesce(nullif(trim(wallet_address), ''), '') <> '')
  )
);

CREATE INDEX IF NOT EXISTS payment_methods_user_id_idx
  ON public.payment_methods (user_id);

CREATE INDEX IF NOT EXISTS payment_methods_user_type_idx
  ON public.payment_methods (user_id, type);

CREATE UNIQUE INDEX IF NOT EXISTS payment_methods_one_default_per_type
  ON public.payment_methods (user_id, type)
  WHERE is_default = true;

CREATE OR REPLACE FUNCTION public.payment_methods_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS payment_methods_updated_at ON public.payment_methods;
CREATE TRIGGER payment_methods_updated_at
  BEFORE UPDATE ON public.payment_methods
  FOR EACH ROW
  EXECUTE FUNCTION public.payment_methods_set_updated_at();

ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can select own payment methods" ON public.payment_methods;
CREATE POLICY "Users can select own payment methods"
  ON public.payment_methods
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own payment methods" ON public.payment_methods;
CREATE POLICY "Users can insert own payment methods"
  ON public.payment_methods
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own payment methods" ON public.payment_methods;
CREATE POLICY "Users can update own payment methods"
  ON public.payment_methods
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own payment methods" ON public.payment_methods;
CREATE POLICY "Users can delete own payment methods"
  ON public.payment_methods
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.payment_methods TO authenticated;


-- ========== 20260826180000_subscriptions_and_activity.sql ==========

-- Subscriptions lifecycle + user activity logs.
-- profiles.plan remains a cached effective plan for UI/quick reads.
-- Authoritative entitlement: active subscription with ends_at > now().

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  plan TEXT NOT NULL CHECK (plan IN ('pro', 'business')),
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'expired', 'canceled', 'pending')),
  starts_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ends_at TIMESTAMPTZ NOT NULL,
  cancel_at_period_end BOOLEAN NOT NULL DEFAULT false,
  canceled_at TIMESTAMPTZ,
  activated_by UUID REFERENCES auth.users (id) ON DELETE SET NULL,
  source TEXT NOT NULL DEFAULT 'admin_manual'
    CHECK (source IN ('admin_manual', 'crypto', 'stripe', 'other')),
  payment_reference TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS subscriptions_user_id_idx ON public.subscriptions (user_id);
CREATE INDEX IF NOT EXISTS subscriptions_status_idx ON public.subscriptions (status);
CREATE INDEX IF NOT EXISTS subscriptions_ends_at_idx ON public.subscriptions (ends_at);
CREATE INDEX IF NOT EXISTS subscriptions_user_active_idx
  ON public.subscriptions (user_id, status, ends_at DESC);

CREATE OR REPLACE FUNCTION public.subscriptions_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS subscriptions_updated_at ON public.subscriptions;
CREATE TRIGGER subscriptions_updated_at
  BEFORE UPDATE ON public.subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION public.subscriptions_set_updated_at();

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Users may read only their own subscription rows (no insert/update/delete from client).
DROP POLICY IF EXISTS "Users can select own subscriptions" ON public.subscriptions;
CREATE POLICY "Users can select own subscriptions"
  ON public.subscriptions
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

GRANT SELECT ON public.subscriptions TO authenticated;
GRANT ALL ON public.subscriptions TO service_role;

-- Effective plan: paid only while an active (non-expired) subscription exists.
CREATE OR REPLACE FUNCTION public.get_effective_plan(p_user_id uuid)
RETURNS public.user_plan
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (
      SELECT s.plan::public.user_plan
      FROM public.subscriptions s
      WHERE s.user_id = p_user_id
        AND s.status = 'active'
        AND s.ends_at > timezone('UTC', now())
      ORDER BY s.ends_at DESC
      LIMIT 1
    ),
    'free'::public.user_plan
  );
$$;

REVOKE ALL ON FUNCTION public.get_effective_plan(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_effective_plan(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_effective_plan(uuid) TO service_role;

-- Invoice limit uses effective plan (not stale profiles.plan alone).
CREATE OR REPLACE FUNCTION public.enforce_invoice_plan_limit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  effective_plan public.user_plan;
  monthly_count integer;
BEGIN
  effective_plan := public.get_effective_plan(NEW.user_id);

  IF effective_plan = 'free' THEN
    monthly_count := public.count_user_invoices_this_month(NEW.user_id);
    IF monthly_count >= 5 THEN
      RAISE EXCEPTION 'FREE_PLAN_INVOICE_LIMIT'
        USING MESSAGE = 'You have reached the Free plan limit of 3 documents this month. Upgrade to Pro to create unlimited invoices.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_invoice_plan_usage()
RETURNS TABLE (
  plan public.user_plan,
  invoices_this_month integer,
  monthly_limit integer
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    public.get_effective_plan(auth.uid()),
    public.count_user_invoices_this_month(auth.uid()),
    CASE WHEN public.get_effective_plan(auth.uid()) = 'free' THEN 5 ELSE NULL END;
$$;

-- User activity (minimal metadata; no secrets / full payment details).
CREATE TABLE IF NOT EXISTS public.user_activity_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  description TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_activity_logs_user_id_created_at_idx
  ON public.user_activity_logs (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS user_activity_logs_action_idx
  ON public.user_activity_logs (action);

ALTER TABLE public.user_activity_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can select own activity" ON public.user_activity_logs;
CREATE POLICY "Users can select own activity"
  ON public.user_activity_logs
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Inserts only via service role / SECURITY DEFINER helpers.
GRANT SELECT ON public.user_activity_logs TO authenticated;
GRANT ALL ON public.user_activity_logs TO service_role;

CREATE OR REPLACE FUNCTION public.log_user_activity(
  p_user_id uuid,
  p_action text,
  p_description text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_user_id IS NULL OR coalesce(nullif(trim(p_action), ''), '') = '' THEN
    RETURN;
  END IF;
  INSERT INTO public.user_activity_logs (user_id, action, description, metadata)
  VALUES (p_user_id, left(trim(p_action), 80), left(coalesce(p_description, ''), 280), coalesce(p_metadata, '{}'::jsonb));
END;
$$;

REVOKE ALL ON FUNCTION public.log_user_activity(uuid, text, text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.log_user_activity(uuid, text, text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_user_activity(uuid, text, text, jsonb) TO service_role;

-- Expire due subscriptions and sync profiles.plan (cleanup; entitlement still uses get_effective_plan).
CREATE OR REPLACE FUNCTION public.expire_due_subscriptions()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  updated_count integer := 0;
  r RECORD;
BEGIN
  FOR r IN
    SELECT id, user_id, plan
    FROM public.subscriptions
    WHERE status = 'active'
      AND ends_at <= timezone('UTC', now())
  LOOP
    UPDATE public.subscriptions
    SET status = 'expired',
        updated_at = now()
    WHERE id = r.id;

    -- Only downgrade profile if no other active sub remains.
    IF public.get_effective_plan(r.user_id) = 'free' THEN
      UPDATE public.profiles
      SET plan = 'free',
          updated_at = now()
      WHERE id = r.user_id
        AND plan <> 'free';
    END IF;

    updated_count := updated_count + 1;
  END LOOP;

  RETURN updated_count;
END;
$$;

REVOKE ALL ON FUNCTION public.expire_due_subscriptions() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.expire_due_subscriptions() TO service_role;

